# nixpacks.toml
# Memberitahu Railway untuk menginstal Node.js DAN Python
providers = ["nodejs", "python"]

[phases.setup]
# Instal library sistem yang dibutuhkan oleh h5py
aptPkgs = ["libhdf5-dev", "pkg-config"]

[phases.install]
# Menjalankan kedua perintah instalasi
cmds = ["npm install", "pip install -r requirements.txt"]